package com.askokov.rtsc.common;

import java.io.File;
import java.io.FileOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import android.content.Context;
import android.os.Environment;
import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class ReportGenerator {
    private static final String FONT_PATH = "/assets/fonts/DroidSans.ttf";

    private Font catFont;
    private Font redFont;
    private Font subFont;
    private Font smallBold;

    public ReportGenerator() throws Exception {
        //BaseFont baseFont = BaseFont.createFont("/system/fonts/Comic.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        BaseFont baseFont = BaseFont.createFont(FONT_PATH, "CP1251", BaseFont.EMBEDDED);
        catFont = new Font(baseFont, 18, Font.BOLD);
        redFont = new Font(baseFont, 12, Font.NORMAL, BaseColor.RED);
        subFont = new Font(baseFont, 16, Font.BOLD);
        smallBold = new Font(baseFont, 12, Font.BOLD);
    }

    private File createFile(String fileName, Context context) {
        final String APPLICATION_PACKAGE_NAME = context.getPackageName();
        File path = new File(Environment.getExternalStorageDirectory(), APPLICATION_PACKAGE_NAME);
        if (!path.exists()) {
            path.mkdir();
        }
        return new File(path, fileName);
    }

    public String createPDF(String fileName, Context context) throws Exception {
        File file = createFile(fileName, context);

        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(file));
        document.open();
        addMetaData(document);
        addTitlePage(document);
        addContent(document);
        document.close();

        return file.getAbsolutePath();
    }

    public String createPDF(String fileName, Context context, java.util.List<PInfo> list) throws Exception {
        File file = createFile(fileName, context);

        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(file));
        document.open();
        addMetaData(document);
        addTitlePage(document);
        addTableContent(document, list);
        document.close();

        return file.getAbsolutePath();
    }

    private void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Aliaksei Skokau");
        document.addCreator("Алексей Скоков");
    }

    private void addTitlePage(Document document) throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Статистика запуска программ на планшете", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

        preface.add(new Paragraph("Отчет создан: " + df.format(new Date()), smallBold));
        addEmptyLine(preface, 3);

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("Глава I / Chapter I", catFont);
        anchor.setName("Глава I / Chapter I");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Подкатегория 1 / Subcategory I", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Привет / Hello", subFont));

        subPara = new Paragraph("Подкатегория 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Параграф 1", subFont));
        subCatPart.add(new Paragraph("Параграф 2", subFont));
        subCatPart.add(new Paragraph("Параграф 3", subFont));

        // add a list
        createList(subCatPart);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // add a table
        createTable(subCatPart, new ArrayList<PInfo>());

        // now add all this to the document
        document.add(catPart);

        // Next section
        anchor = new Anchor("Глава II", catFont);
        anchor.setName("Глава II");

        // Second parameter is the number of the chapter
        catPart = new Chapter(new Paragraph(anchor), 1);

        subPara = new Paragraph("Подкатегория", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Важное сообщение", subFont));

        // now add all this to the document
        document.add(catPart);

    }

    private void addTableContent(Document document, java.util.List<PInfo> list) throws DocumentException {
        Chapter chapter = new Chapter(new Paragraph(), 1);

        Paragraph paragraph = new Paragraph("Таблица", subFont);
        addEmptyLine(paragraph, 5);
        chapter.add(paragraph);

        // add a table
        createTable(chapter, list);

        // now add all this to the document
        document.add(chapter);
    }

    private void createTable(Section section, java.util.List<PInfo> list)
        throws BadElementException {
        PdfPTable table = new PdfPTable(4);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Дата", subFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Программа", subFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Время", subFont));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

        for(PInfo info : list) {
            table.addCell(df.format(info.getDate()));
            table.addCell(info.getLabel());
            table.addCell(info.getPackageName());

            long fullSec = info.getFullTime() / 1000000;

            long hour = fullSec / 3600;
            long hourOst = fullSec % 3600;
            long min = hourOst / 60;
            long sec = hourOst % 60;
            String time = String.format("%02dч :%02dмин : %02d сек", hour, min, sec);

            table.addCell(time);
        }

        section.add(table);

    }

    private void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("Текст 1 / Text 1", subFont));
        list.add(new ListItem("Текст 2 / Text 2", subFont));
        list.add(new ListItem("Текст 3 / Text 3", subFont));
        subCatPart.add(list);
    }

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" ", subFont));
        }
    }
}
